const { listServices, getService, upsertService } = require("../store/serviceCatalogStore");
const { createNotification, getNotificationsByUser } = require("../store/notificationStore");
const { savePayment, getPaymentsByApplicationId } = require("../store/paymentStore");
const { create, findByCode, readAll, updateByCode } = require("../store/serviceApplicationStore");
const { getIo } = require("../socket");

const fallbackServices = {
  "ho-tich-khai-sinh": { serviceId: "ho-tich-khai-sinh", id: "ho-tich-khai-sinh", name: "Đăng ký khai sinh", description: "Tiếp nhận, xử lý và trả kết quả đăng ký khai sinh trực tuyến cho công dân.", categoryName: "Hộ tịch", processingTime: "3 ngày làm việc", fee: 0, documents: [{ key: "birthCert", label: "Giấy chứng sinh", required: true }, { key: "idCard", label: "CCCD/CMND người nộp", required: true }, { key: "marriageCert", label: "Giấy đăng ký kết hôn (nếu có)", required: false }], timeline: ["Tiếp nhận hồ sơ", "Kiểm tra tính hợp lệ", "Xử lý chuyên viên", "Phê duyệt / bổ sung", "Trả kết quả"], faq: [] },
  "dat-dai-bien-dong": { serviceId: "dat-dai-bien-dong", id: "dat-dai-bien-dong", name: "Đăng ký biến động đất đai", description: "Tiếp nhận hồ sơ thay đổi, sang tên hoặc cập nhật thông tin quyền sử dụng đất.", categoryName: "Đất đai", processingTime: "5 ngày làm việc", fee: 20000, documents: [{ key: "landCert", label: "Giấy chứng nhận quyền sử dụng đất", required: true }, { key: "mutationForm", label: "Đơn đăng ký biến động", required: true }, { key: "idCard", label: "CCCD/CMND", required: true }], timeline: ["Tiếp nhận hồ sơ", "Kiểm tra tính hợp lệ", "Xử lý chuyên viên", "Phê duyệt / bổ sung", "Trả kết quả"], faq: [] },
  "xay-dung-cap-phep": { serviceId: "xay-dung-cap-phep", id: "xay-dung-cap-phep", name: "Xin cấp phép xây dựng", description: "Nộp hồ sơ đề nghị cấp phép xây dựng và theo dõi trạng thái xử lý.", categoryName: "Xây dựng", processingTime: "7 ngày làm việc", fee: 50000, documents: [{ key: "landCert", label: "Giấy tờ quyền sử dụng đất", required: true }, { key: "design", label: "Bản vẽ thiết kế", required: true }, { key: "idCard", label: "CCCD/CMND", required: true }], timeline: ["Tiếp nhận hồ sơ", "Kiểm tra tính hợp lệ", "Xử lý chuyên viên", "Phê duyệt / bổ sung", "Trả kết quả"], faq: [] },
  "gplx-doi": { serviceId: "gplx-doi", id: "gplx-doi", name: "Đổi giấy phép lái xe", description: "Tiếp nhận hồ sơ đổi giấy phép lái xe theo quy trình điện tử.", categoryName: "Giao thông", processingTime: "4 ngày làm việc", fee: 150000, documents: [{ key: "oldLicense", label: "Giấy phép lái xe cũ", required: true }, { key: "health", label: "Giấy khám sức khỏe", required: true }, { key: "idCard", label: "CCCD/CMND", required: true }], timeline: ["Tiếp nhận hồ sơ", "Kiểm tra tính hợp lệ", "Xử lý chuyên viên", "Phê duyệt / bổ sung", "Trả kết quả"], faq: [] },
  "ho-chieu-pho-thong": { serviceId: "ho-chieu-pho-thong", id: "ho-chieu-pho-thong", name: "Cấp hộ chiếu phổ thông", description: "Tiếp nhận hồ sơ cấp hộ chiếu phổ thông cho công dân đủ điều kiện.", categoryName: "Hộ chiếu", processingTime: "8 ngày làm việc", fee: 200000, documents: [{ key: "photo", label: "Ảnh chân dung", required: true }, { key: "idCard", label: "CCCD/CMND", required: true }], timeline: ["Tiếp nhận hồ sơ", "Kiểm tra tính hợp lệ", "Xử lý chuyên viên", "Phê duyệt / bổ sung", "Trả kết quả"], faq: [] },
  "doanh-nghiep-thanh-lap": { serviceId: "doanh-nghiep-thanh-lap", id: "doanh-nghiep-thanh-lap", name: "Đăng ký thành lập doanh nghiệp", description: "Nộp hồ sơ đăng ký doanh nghiệp và theo dõi tiến trình xử lý.", categoryName: "Doanh nghiệp", processingTime: "3-5 ngày làm việc", fee: 100000, documents: [{ key: "charter", label: "Điều lệ công ty", required: true }, { key: "memberList", label: "Danh sách thành viên/cổ đông", required: true }, { key: "idCard", label: "CCCD/CMND người đại diện", required: true }], timeline: ["Tiếp nhận hồ sơ", "Kiểm tra tính hợp lệ", "Xử lý chuyên viên", "Phê duyệt / bổ sung", "Trả kết quả"], faq: [] }
};

function generateApplicationCode() { const now = new Date(); return `HS-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, "0")}${String(now.getDate()).padStart(2, "0")}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; }
function validateForm(formData) { const errors = {}; if (!formData?.fullName?.trim()) errors.fullName = "Họ tên là bắt buộc"; if (!/^[0-9]{12}$/.test(formData?.citizenId || "")) errors.citizenId = "CCCD phải đủ 12 số"; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData?.email || "")) errors.email = "Email không đúng định dạng"; if (!/^[0-9]{10,11}$/.test(formData?.phone || "")) errors.phone = "Số điện thoại không hợp lệ"; if (!formData?.address?.trim()) errors.address = "Địa chỉ là bắt buộc"; return errors; }
function userId(req) { return req.user?.id || req.user?._id || req.user?.sub || req.user?.email || null; }
function resolveService(serviceId) { const local = fallbackServices[serviceId]; if (local) return Promise.resolve(local); return getService(serviceId).then((svc) => svc || null); }

exports.getServices = async (req, res) => { const q = String(req.query.q || "").toLowerCase(); const category = String(req.query.category || "").toLowerCase(); const items = await listServices(); const filtered = items.filter((s) => { const text = `${s.name || ""} ${s.description || ""} ${s.categoryName || ""}`.toLowerCase(); return (!q || text.includes(q)) && (!category || String(s.categoryId || s.categoryName || "").toLowerCase() === category); }); res.json({ services: filtered }); };
exports.getServiceById = async (req, res) => { const service = await resolveService(req.params.serviceId); if (!service) return res.status(404).json({ message: "Không tìm thấy dịch vụ" }); res.json(service); };
exports.submitApplication = async (req, res) => { const { serviceId, formData = {}, attachments = [], paymentMethod = "VNPay" } = req.body; if (!serviceId) return res.status(400).json({ message: "Thiếu serviceId" }); const service = await resolveService(serviceId); if (!service) return res.status(404).json({ message: "Dịch vụ không tồn tại" }); const errors = validateForm(formData); if (Object.keys(errors).length) return res.status(400).json({ message: "Dữ liệu không hợp lệ", errors }); const applicationCode = generateApplicationCode(); const application = { applicationCode, applicationId: applicationCode, id: applicationCode, userId: userId(req), serviceId, serviceName: service.name, formData, citizenName: formData.fullName, phone: formData.phone, email: formData.email, attachments, paymentMethod, status: "PENDING", paymentStatus: "UNPAID", progress: 10, history: [{ at: new Date().toISOString(), status: "PENDING", note: "Hồ sơ đã được nộp" }], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), fee: service.fee || 0 }; await create(application); res.status(201).json({ message: "Nộp hồ sơ thành công", applicationCode, application }); };
exports.getApplicationByCode = async (req, res) => { const application = await findByCode(req.params.applicationCode); if (!application) return res.status(404).json({ message: "Không tìm thấy hồ sơ" }); const payments = await getPaymentsByApplicationId(req.params.applicationCode); const notifications = application.userId ? await getNotificationsByUser(application.userId) : []; res.json({ application, payments, notifications, timeline: application.history || [] }); };
exports.getMyApplications = async (req, res) => { const items = await readAll(); const filtered = items.filter((x) => !userId(req) || x.userId === userId(req)); res.json({ applications: filtered.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)) }); };
exports.trackApplication = async (req, res) => { const application = await findByCode(req.params.applicationCode); if (!application) return res.status(404).json({ message: "Không tìm thấy hồ sơ" }); const payments = await getPaymentsByApplicationId(req.params.applicationCode); const notifications = application.userId ? await getNotificationsByUser(application.userId) : []; res.json({ application, payments, notifications, timeline: application.history || [] }); };
exports.payForApplication = async (req, res) => { const { applicationCode, paymentMethod = "VNPAY", amount } = req.body; const application = await findByCode(applicationCode); if (!application) return res.status(404).json({ message: "Không tìm thấy hồ sơ" }); const payment = { paymentId: `PAY-${Date.now()}`, applicationId: applicationCode, amount: amount || application.fee || 0, paymentMethod, transactionId: `TX-${Date.now()}`, paymentStatus: "PAID", createdAt: new Date().toISOString() }; await savePayment(payment); await updateByCode(applicationCode, { ...application, paymentStatus: "PAID", status: "APPROVED", updatedAt: new Date().toISOString(), history: [...(application.history || []), { at: new Date().toISOString(), status: "PAID", note: "Thanh toán thành công" }] }); await createNotification({ notificationId: `NTF-${Date.now()}`, userId: application.userId, applicationId: applicationCode, title: "Thanh toán thành công", message: `Hồ sơ ${applicationCode} đã được thanh toán.`, createdAt: new Date().toISOString() }); try { getIo().to(`user_${application.userId}`).emit("service-application-updated", { applicationCode, paymentStatus: "PAID" }); } catch {} res.json({ message: "Thanh toán thành công", payment }); };
exports.adminCreateService = async (req, res) => { const body = req.body || {}; if (!body.serviceId && !body.id) return res.status(400).json({ message: "Thiếu serviceId" }); const serviceId = String(body.serviceId || body.id).trim(); const item = { serviceId, id: serviceId, name: String(body.name || "").trim(), description: String(body.description || "").trim(), categoryId: String(body.categoryId || "").trim(), categoryName: String(body.categoryName || body.category || "Khác").trim(), fee: Number(body.fee || 0), processingTime: String(body.processingTime || "Đang cập nhật"), documents: Array.isArray(body.documents) ? body.documents : [], faq: Array.isArray(body.faq) ? body.faq : [], timeline: Array.isArray(body.timeline) ? body.timeline : [], active: body.active !== false, updatedAt: new Date().toISOString(), createdAt: body.createdAt || new Date().toISOString() }; if (!item.name) return res.status(400).json({ message: "Tên dịch vụ là bắt buộc" }); await upsertService(item); res.status(201).json({ message: "Đã lưu dịch vụ", service: item }); };
exports.adminUpdateService = async (req, res) => { const serviceId = req.params.serviceId; const current = await resolveService(serviceId); if (!current) return res.status(404).json({ message: "Không tìm thấy dịch vụ" }); const next = { ...current, ...req.body, serviceId, id: serviceId, updatedAt: new Date().toISOString() }; await upsertService(next); res.json({ message: "Đã cập nhật dịch vụ", service: next }); };
exports.adminDeleteService = async (req, res) => { const serviceId = req.params.serviceId; const current = await resolveService(serviceId); if (!current) return res.status(404).json({ message: "Không tìm thấy dịch vụ" }); await upsertService({ ...current, active: false, deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); res.json({ message: "Đã xóa dịch vụ" }); };
